name: Oitc
version: '2.0.0-mc1.8'
main: net.velosia.oitc.Oitc
authors: [ Zeykra_ ]
commands:
  oitc:
    description: "command principale du plugin oitc"
softdepend:
  - HolographicDisplays
  - Citizens
